#Faça um programa que receba um número qualquer e mostre na tela sua tabuada
v = int(input('Digite o valor: '))
print('A tabuada de {} é:\n{}x0  = {}'.format(v,v, v*0))
print('{}x1  = {}'.format(v, v*1))
print('{}x2  = {}'.format(v, v*2))
print('{}x3  = {}'.format(v, v*3))
print('{}x4  = {}'.format(v, v*4))
print('{}x5  = {}'.format(v, v*5))
print('{}x6  = {}'.format(v, v*6))
print('{}x7  = {}'.format(v, v*7))
print('{}x8  = {}'.format(v, v*8))
print('{}x9  = {}'.format(v, v*9))
print('{}x10 = {}'.format(v, v*10))